config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resource :bx, only: [:show, :index]
  #
  # root 'bx#index'
  resource :markets do
    get 'bx', to: 'markets#bx'
  end


  root 'markets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/binance_service.rb
class BinanceService

  BINANCE_BASE_API = "https://api.binance.com/api/v1/"

  # NOT LISTED GNO

  def self.all_prices
    request = Typhoeus.get("#{BINANCE_BASE_API}ticker/allPrices")
    JSON.parse(request.response_body)
  end

  def self.price(currency)
    request = Typhoeus.get("#{BINANCE_BASE_API}ticker/24hr?symbol=#{currency.upcase}BTC")
    response = JSON.parse(request.response_body)
    response["askPrice"]
  end

  def self.price_usd(currency)
    satoshi = price(currency.upcase).to_f
    btc_price = CmcService.btc_usd.to_f

    satoshi * btc_price
  end

  def self.tradeable_markets
    prices = all_prices
    prices = prices.select{ |c| BxService::TRADEABLE.include? c["symbol"][0..2] }
                   .reject{|x| x["symbol"][3..-1] == "USDT" }
                   .reject{|x| x["symbol"][3..-1] == "BNB" }
  end

  def self.tradeable_btc_markets
    markets = tradeable_markets.reject{|x| x["symbol"][-3..-1] == "ETH" }
    btc_price = CmcService.btc_usd.to_f

    markets_with_usd = markets.each { |m|
      usd_price = m["price"].to_f * btc_price
      price_hash = { "usd_price" => usd_price }
      m.merge!(price_hash)
    }

    return markets_with_usd
  end

end

app/models/concerns/bx_service.rb
class BxService
  require 'openssl'
  require 'typhoeus'
  
  BX_KEY = ENV['BX_API_KEY']
  BX_SECRET = ENV['BX_API_SECRET']
  BX_BASE_ENDPOINT = "https://bx.in.th/api/"
  TRADEABLE = %w(ETH DAS REP BCH EVX GNO LTC OMG XRP XZC).freeze
  
  # DASH LISTED AS DAS ON BX, LISTED AS DASH ON BINANCE/BITTREX
  
  # PUBLIC API
  def self.get_market_data
    request = Typhoeus.get(BX_BASE_ENDPOINT)
    JSON.parse(request.response_body).with_indifferent_access
  end
  
  def self.get_pairings
    request = Typhoeus.get("#{BX_BASE_ENDPOINT}pairing/")
    JSON.parse request.response_body
  end
  
  def self.orderbook(pair_id)
    request = Typhoeus.get("#{BX_BASE_ENDPOINT}orderbook/?pairing=#{pair_id}")
    JSON.parse request.response_body
  end
  
  # PRIVATE API
  def self.generate_signature
    message = BX_KEY + get_nonce + BX_SECRET
    signature = OpenSSL::Digest::SHA256.new(message)
    
    return signature
  end
  
  def self.get_balances
    body = {
      key: BX_KEY,
      nonce: get_nonce,
      signature: generate_signature
    }.to_json
    
    request = Typhoeus::Request.new(
      "#{BX_BASE_ENDPOINT}balance/",
      method: :post,
      body: body,
      params: {},
      headers: { "Content-Type" => "application/json" }
    ).run
    
    JSON.parse request.response_body
  end
  
  def self.get_nonce
    DateTime.now.strftime('%Q')
  end
  
end

app/models/concerns/cmc_service.rb
class CmcService
  
  BASE_ENDPOINT = "https://api.coinmarketcap.com/v1/ticker/"
  
  def self.btc_usd
    request = Typhoeus.get("#{BASE_ENDPOINT}bitcoin/")
    
    response = JSON.parse(request.response_body)
    response[0]["price_usd"]
  end
  
end

app/models/concerns/currency_layer.rb
class CurrencyLayer
  require 'typhoeus'
  
  CL_KEY = ENV['CURRENCY_LAYER_KEY']
  CL_BASE_ENDPOINT = "http://apilayer.net/api/"
  
  def self.usd_thb
    request_url = "#{CL_BASE_ENDPOINT}live?access_key=#{CL_KEY}&currencies=THB"
    request = Typhoeus.get(request_url)
    
    response = JSON.parse(request.response_body).with_indifferent_access
    response[:quotes][:USDTHB]
  end  
  
  
end

app/models/concerns/poloniex.rb
class Poloniex
  require 'openssl'
  require 'Base64'
  
  POLONIEX_KEY = ENV['POLONIEX_KEY']
  POLONIEX_SECRET = ENV['POLONIEX_SECRET']
  TRADING_API = "https://poloniex.com/tradingApi"

  def self.ticker
    request = Typhoeus.get("https://poloniex.com/public?command=" + "returnTicker")
    JSON.parse request.response_body
  end
  
  def self.get_nonce
    DateTime.now.strftime('%Q')
  end
  
  def self.account_balances
    nonce = self.get_nonce
    request_url = "#{TRADING_API}?command=returnDepositAddress" +"&nonce=#{nonce}"
    headers = {
      'Sign' => self.signature,
      'Key' => POLONIEX_KEY
    }
    
    response = Typhoeus::Request.new(
      request_url,
      method: "post",
      body: '',
      headers: headers
    ).run
    response
  end  
  
  def self.signature(post_data='')
    OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), POLONIEX_SECRET, post_data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController

  def index
    @bx = @bx_pairings = BxService.get_market_data
    @bx_pairings = @bx_pairings.select{ |k,v| v[:primary_currency] == "THB" }
    @binance = BinanceService.tradeable_btc_markets
    @poloniex = Poloniex.ticker
    @btc = CmcService.btc_usd
    @thb = CurrencyLayer.usd_thb
  end

  def bx
    @bx_pairings = BxService.get_market_data
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bx_helper.rb
module BxHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      .flex-container {
        display: flex;
        flex-direction: flow;
        justify-content:: center; 
      }
    
    
    </style>
    
    <title>TradeMachine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/markets/bx.html.erb
<style>
  table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
  }
  th, td {
      padding: 5px;
      text-align: right;
  }
</style>

<h1>bx.in.th markets</h1>
<table>
  <tr>
    <th>Market</th>
    <th>Change</th>
    <th>Price</th>
    <th>24HR volume</th>
  </tr>

  <% @bx_pairings.each do |pair| %>
    <% pair = pair[1] %>
    <tr>
      <% last_price = pair[:last_price].to_s %>

      <td><%= "#{pair[:primary_currency]}_#{pair[:secondary_currency]}" %></td>
      <td><%= "#{pair[:change]} #{pair[:primary_currency]}" %></td>
      <td><%= last_price.include?("e-") ? ("%.8f" % last_price) : last_price %></td>
      <td><%= pair[:volume_24hours].round(2) %></td>
    </tr>
  <% end %>
</table>

app/views/markets/index.html.erb
<style>
  table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
  }
  th, td {
      padding: 5px;
      text-align: left;
  }
</style>

<h2>1 USD = <%= @thb %> THB</h2>

<table>
  <tr>
    <th>COIN</th>
    <th colspan="2">BX.IN.TH</th>
    <th colspan="4">binance</th>
    <th colspan="4">poloniex</th>
  </tr>
  <tr>
    <td></td>
    <td>THB</td>
    <td>USD</td>
    <!-- binance -->
    <td>USD</td>
    <td>BTC</td>
    <td>usd diff</td>
    <td>% diff</td>
    <!-- poloniex -->
    <td>USD</td>
    <td>BTC</td>
    <td>usd diff</td>
    <td>% diff</td>
  </tr>
  <% @bx_pairings.each_value do |pair| %>

    <% bx_usd_price = (pair[:orderbook][:bids][:highbid] / @thb).round(2) %>
    <% available_binance = @binance.select { |c| c["symbol"][0..2] == pair[:secondary_currency] }.first %>

    <% if pair[:secondary_currency] == "DAS" %>
      <% available_poloniex = @poloniex["BTC_DASH"] %>
    <% else %>
      <% available_poloniex = @poloniex.select { |p| p[4..-1] == pair[:secondary_currency] }.first %>
      <% available_poloniex = available_poloniex[1] rescue nil %>
    <% end %>

    <tr>
      <th><%= pair[:secondary_currency] %></th>

      <!-- BX COLUMNS -->
      <td><%= pair[:last_price]%></td>
      <td><%= bx_usd_price %></td>

      <% unless available_binance.blank? %>
        <td><%= bin_usd_price = available_binance["usd_price"].round(2) %></td>
        <td><%= available_binance["price"] %></td>
        <td><%= diff = ( bx_usd_price - available_binance["usd_price"]).round(2)  %></td>
        <td><%= (( bx_usd_price - bin_usd_price) / (( bx_usd_price + bin_usd_price) / 2) * 100).round(2) %></td>
      <% else %>
        <td></td><td></td><td></td><td></td>
      <% end %>

      <% unless available_poloniex.blank? %>
        <td><%= polo_usd_price = (available_poloniex["lowestAsk"].to_f * @btc.to_f).round(2) %></td>
        <td><%= available_poloniex["lowestAsk"] %></td>
        <td><%= ( bx_usd_price - polo_usd_price ).round(2) %></td>
        <td><%= (( bx_usd_price - polo_usd_price) / (( bx_usd_price + polo_usd_price) / 2) * 100).round(2) %></td>
      <% else %>
        <td></td><td></td><td></td><td></td>
      <% end %>
    </tr>

  <% end %>

</table>

app/views/shared/_header.html.erb
<div class='flex-container'>
  <script type="text/javascript" src="https://files.coinmarketcap.com/static/widget/currency.js"></script>
  <div class="coinmarketcap-currency-widget" data-currency="bitcoin" data-base="USD" ></div>
  <div class="coinmarketcap-currency-widget" data-currency="ethereum" data-base="USD" ></div>
  <div class="coinmarketcap-currency-widget" data-currency="ripple" data-base="USD" ></div>
  <div class="coinmarketcap-currency-widget" data-currency="litecoin" data-base="USD" ></div>
</div>

<span><%= link_to "HOME", root_path %> // <%= link_to "BX", bx_markets_path %></span>